#!/usr/bin/env bash
set -euo pipefail

# Establish a known initial state. Randomized usernames/groups are generated by
# the host runner and therefore cannot already exist in this base image.
mkdir -p /srv
chmod 0755 /srv
